name: Docs

env:
  TERM: screen-256color

on:
  push:
    branches: ["master", "main"]
    paths:
      - "docs/**/*"
      - "mkdocs.yml"
    tags:
      - "v*"

jobs:

  docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install mkdocs-material

      - run: mkdocs gh-deploy --force
